# Generated by Django 5.2 on 2025-04-22 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Django', 'Django'), ('React', 'React'), ('SQL', 'SQL'), ('Java', 'Java'), ('C#', 'C#'), ('AWS', 'AWS'), ('Docker', 'Docker'), ('Machine Learning', 'Machine Learning'), ('Data Analysis', 'Data Analysis'), ('UI/UX Design', 'UI/UX Design'), ('SEO', 'SEO'), ('Graphic Design', 'Graphic Design')], max_length=255, unique=True)),
                ('tag_type', models.CharField(blank=True, choices=[('Skill', 'Skill'), ('Tool', 'Tool'), ('Language', 'Language'), ('Other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/profiles/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('graduation_year', models.CharField(blank=True, max_length=10, null=True)),
                ('is_recruiter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_date', models.DateField()),
                ('location', models.CharField(default='Not Specified', max_length=200)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Apprenticeship', 'Apprenticeship'), ('Internship', 'Internship'), ('Traineeship', 'Traineeship'), ('Contract', 'Contract'), ('Casual', 'Casual'), ('Seasonal', 'Seasonal'), ('Commission', 'Commission'), ('Leased', 'Leased'), ('Contingent', 'Contingent'), ('Probation', 'Probation'), ('Freelance', 'Freelance'), ('Temporary', 'Temporary')], default='Full Time', max_length=100)),
                ('industry', models.CharField(blank=True, choices=[('IT', 'Information Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Marketing', 'Marketing'), ('Engineering', 'Engineering'), ('Retail', 'Retail'), ('Customer Service', 'Customer Service'), ('Legal', 'Legal')], max_length=100, null=True)),
                ('experience_level', models.CharField(choices=[('Fresher', 'Fresher'), ('Entry', 'Entry-level'), ('Mid', 'Mid-level'), ('Senior', 'Senior-level'), ('Manager', 'Manager'), ('Director', 'Director')], default='Fresher', max_length=50)),
                ('work_environment', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], max_length=20, null=True)),
                ('salary', models.CharField(blank=True, choices=[('Below 30K', 'Below 30K'), ('30K-50K', '30K-50K'), ('50K-80K', '50K-80K'), ('80K-100K', '80K-100K'), ('100K+', '100K+')], max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('vacancy', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('graduation_year', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/job_posts/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Job Post',
                'verbose_name_plural': 'Job Posts',
            },
        ),
    ]
