# Generated by Django 5.2 on 2025-04-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('recruiter', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='company_name',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='companies',
            field=models.ManyToManyField(related_name='recruiters', to='company.company'),
        ),
    ]
