# Generated by Django 5.2 on 2025-04-22 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Consultant', 'Consultant'), ('Analyst', 'Analyst'), ('Manager', 'Manager'), ('UI/UX Designer', 'UI/UX Designer'), ('HR', 'HR'), ('Operations', 'Operations')], max_length=100, null=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('ideal_candidate', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], max_length=20, null=True)),
                ('industry', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Education', 'Education'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Transportation', 'Transportation'), ('Energy', 'Energy'), ('Other', 'Other')], max_length=50, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('1-3 years', '1-3 years'), ('3-5 years', '3-5 years'), ('5+ years', '5+ years')], max_length=20, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('salary', models.PositiveIntegerField(default=30000)),
                ('is_available', models.BooleanField(default=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.company')),
            ],
        ),
    ]
